import '@/styles/app.scss';
import type { Metadata } from 'next';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';

export const metadata: Metadata = {
    title: 'Home page',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body>
                <Header />
                <main className={'main'}>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
